import jsPDF from 'jspdf';
import { toPng } from 'html-to-image';

/**
 * Hook for managing the generation and downloading of PDF proposals.
 * Uses html-to-image and jspdf to capture the user's workspace and generate a report.
 * 
 * @returns An object containing the handleExportPDF function.
 */

export function usePDFExport() {
  const handleExportPDF = async () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("AI Solar Proposal", 20, 20);
    doc.setFontSize(12);
    doc.text("Generated by AI Solar Roof Designer", 20, 30);
    
    try {
      const canvasElement = document.getElementById('roof-canvas-container');
     
      if (canvasElement) {
        const imgData = await toPng(canvasElement, {
          cacheBust: true,
          pixelRatio: 2,
          backgroundColor: '#050505',
          style: { transform: 'none' }
        });
        
        doc.addImage(imgData, 'PNG', 20, 40, 170, 100);
      }
      
      doc.save("Solar_Proposal.pdf");
    } catch (err: any) {
      console.error("PDF Export failed:", err);
      alert(`PDF Export failed: ${err.message || err}`);
    }
  };

  return { handleExportPDF };
}
