import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Hook for managing the generation and downloading of PDF proposals.
 * Uses html2canvas and jspdf to capture the user's workspace and generate a report.
 * 
 * @returns An object containing the handleExportPDF function.
 */

export function usePDFExport() {
  const handleExportPDF = async () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("AI Solar Proposal", 20, 20);
    doc.setFontSize(12);
    doc.text("Generated by AI Solar Roof Designer", 20, 30);
    
    const canvasElement = document.getElementById('roof-canvas-container');
   
    if (canvasElement) {
      const canvas = await html2canvas(canvasElement);
      const imgData = canvas.toDataURL('image/png');
      doc.addImage(imgData, 'PNG', 20, 40, 170, 100);
    }
    
    doc.save("Solar_Proposal.pdf");
  };

  return { handleExportPDF };
}
